variables:
  projectDirectory: 'AzureDevOpsExampleApp'
trigger:
  - dev
jobs:
  - job: Android
    displayName: 'Android Build'
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: |
        echo 'Hello Wold'
      displayName: Say Hello
    - script: |
        ./gradlew assembleRecette
      env:
        JAVA_HOME: $(JAVA_HOME_11_X64)
        PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
      displayName: Create Apk

    - task: CopyFiles@2
      condition: true
      inputs:
        contents: '**/?(*.apk)'
        targetFolder: '$(build.artifactStagingDirectory)'
        flattenFolders: true
    - script: |
        la -la
      displayName: Create Apk